#!/bin/sh

# Use neovim for vim if present
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Basic navigation
alias v="vim"
alias la="ls -A"
alias ll="ls -lA"
alias mkd="mkdir -pv"
alias rm="rm -v"
alias ka="killall"
alias sdn="sudo shutdown -h now"

# Git
alias g="git"
alias gs="git status"
alias ga="git add"

# Homebrew
alias b="brew"
alias bc="brew cask"
alias bt="brew tap"
alias bi="brew install"
alias bic="brew cask install"

